services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT}:${APP_PORT}"

    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=${JAVA_OPTS}
      - SERVER_PORT=${APP_PORT}
    networks:
      - render-network
    restart: on-failure:3


networks:
  render-network:
    driver: bridge
